name: Check Broken Links

on: [push, pull_request]

jobs:
  check-links:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - name: Attendre le déploiement sur github pages
      run: sleep 120
    - run: npm install broken-link-checker
    - run: npx blc https://jeremydallain.github.io/test-actions -rov